apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: router-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
        - path: /hs
          pathType: ImplementationSpecific
          backend:
            service:
              name:  {{ .Values.fullName }}
              port:
                number: {{ .Values.service.httpPort }}