apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName}}
  labels:
    app: {{ .Values.selectorLabel }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.httpPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    app: {{ .Values.selectorLabel }}


